### PR TITLE
ADD Mail pre meetup Agosto

### PR DESCRIPTION
**Pull request by cristofer-dev**
Changes to be committed:
	new file:   data/2018-08.json
	new file:   emails/2018/08/pre-meetup.md

### CODE REVIEW

**Comment by cristofer-dev** [comment]
@enBonnet Check, please!

**Comment by enBonnet** [comment]
@cristofer-dev Cuando lo quieres mandar?

Falta agregar la charla de Raul

**Comment by cristofer-dev** [comment]
Mañana!
Raul aún no abre issue!

**Review by enBonnet — COMMENTED** [review]
Aprobado para mandarse

**Review by enBonnet — APPROVED** [review]
Listo

**Pull request merged**
